# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: middleman_jasmine_sample 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "middleman_jasmine_sample"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ludwig Bratke"]
  s.date = "2014-04-03"
  s.description = "TODO: longer description of your gem"
  s.email = "bratke@stroeermobilemedia.de"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "config.rb",
    "public/javascripts/Player.js",
    "public/javascripts/Song.js",
    "source/images/background.png",
    "source/images/middleman.png",
    "source/index.html.erb",
    "source/javascripts/all.js",
    "source/layouts/layout.erb",
    "source/stylesheets/all.css",
    "source/stylesheets/normalize.css",
    "spec/javascripts/PlayerSpec.js",
    "spec/javascripts/helpers/SpecHelper.js",
    "spec/javascripts/support/jasmine.yml",
    "spec/javascripts/support/jasmine_helper.rb"
  ]
  s.homepage = "http://github.com/bratke/middleman_jasmine_sample"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.0"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<middleman>, ["~> 3.2.2"])
      s.add_runtime_dependency(%q<middleman-livereload>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<wdm>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<middleman-jasmine>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<middleman>, ["~> 3.2.2"])
      s.add_dependency(%q<middleman-livereload>, ["~> 3.1.0"])
      s.add_dependency(%q<wdm>, ["~> 0.1.0"])
      s.add_dependency(%q<middleman-jasmine>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<middleman>, ["~> 3.2.2"])
    s.add_dependency(%q<middleman-livereload>, ["~> 3.1.0"])
    s.add_dependency(%q<wdm>, ["~> 0.1.0"])
    s.add_dependency(%q<middleman-jasmine>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

